---
sudo: false

language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

matrix:
  allow_failures:
    - php: '7.0'
    - php: '7.1'
  fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer install

script:
  - vendor/bin/phpunit
...